name: SumselFire CI Training Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib

      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ \
            --env-manager=local \
            --experiment-name=sumselfire-fire-risk-ci \
            -P data_path=fire_risk_dataset_preprocessing/fire_risk_preprocessed.csv

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            mlruns/
            confusion_matrix.png
            feature_importance.png
            classification_report.txt

      - name: Commit mlruns to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mlruns/
          git diff --staged --quiet || git commit -m "ci: update mlruns artifacts [skip ci]"
          git push 

      - name: Build Docker Image
        run: |
          python -m mlflow models build-docker \
            -m "mlruns/331138227251465126/bf6604ff91bf4031b19b64965d5a6fa2/artifacts/random_forest_model" \
            -n ${{ secrets.DOCKERHUB_USERNAME }}/sumselfire-fire-risk \
            --env-manager local

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sumselfire-fire-risk:latest
